name: syntax
on: push
jobs:
    task1:
        runs-on: ubuntu-latest
        steps:
            - run: echo Checker-c works
            - run: echo Made by Andrei Radu
            - run: gcc ./add.c 1 2